In [29]:
# Basics 
# dimensions are called axes with 0 = rows, 1 = columns

"""

Attributes of the Numpy Array 

ndarray.ndim: nuber of dimensions 
ndarray.shape: dimensions of the array 
ndarray.size: toal number of elements in the array 
ndarray.dtype: object with information about the data type
ndarray.itemsize: size in bytes of the each element 
ndarray.data: address of the buffer with the actual elemens 
"""

import numpy as np

data: np.ndarray = np.array([[1, 2, 3] for _ in range(3)])

print(data)
print(f"Dimensions: {data.ndim}")
print(f"Shape: {data.shape}")
print(f"Size : {data.size}")
print(f"dtype : {data.dtype}")
print(f"itemsize : {data.itemsize}")
print(f"data: {data.data}")

# Array Creation with specified data type 

floating_zeros = np.array((4, 4), dtype=np.float64)
rang = np.arange(0, 100, 2, dtype=np.int8)

# due to arange being unpredictable with floaing point number, linspace was created to set floating space
# start, 
# end, 
# number of points in between end and start
lins = np.linspace(0, 0.5, 100)

A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A * B) # element wise product (dimensions must mathc)
print(A @ B) # Treats matrices as in math, means for A@B[0, 0] we get <A[0, 0], [B[0, 1], B[1, 1]]>

# Operations like += *= act inplace
# Others create new arrays 


# Memberfunctions

print(f"Sum of each column {A.sum(axis=0)}") # we are summing all row vectors
print(f"Sum of each row {A.sum(axis=1)}") # we are summing all column vectors


# creating array with an specific number of dimensions
data2: np.ndarray = np.array([1, 2, 3, 4], ndmin=2)

# Each axis hets is own index for [start:stop:step, _:_:_, ..., _:_:_]
print(f'{data[:,0]}')
print(data.T)
data.T[:, 0]

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Dimensions: 2
Shape: (3, 3)
Size : 9
dtype : int64
itemsize : 8
data: <memory at 0x7f2b77f285f0>
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
Sum of each column [1 2]
Sum of each row [2 1]
[1 1 1]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


array([1, 2, 3])